Repository FlawDetector-team-yes/FlawDetector-team-yes, pull requests merged in 2024-08, with the labels that each got.

#4 chore: PR 테스트
  src/components/.gitkeep
Labels: chore

#7 chore: 공통 icon, font
  public/images/chat-active.png
  public/images/chat.png
  public/images/check.png
  public/images/circle-green.png
  public/images/circle-success.png
  public/images/double-arrow.png
  public/images/file.png
  public/images/folder-dashed.png
  public/images/folder-open.png
  public/images/left-arrow-pagination.png
  public/images/left-violet-arrow.png
  public/images/loading.png
  public/images/magnifier.png
  public/images/menu-dot.png
  public/images/menu-repo-folder.png
  public/images/pin-active.png
  public/images/pin.png
  public/images/plus.png
  public/images/reload.png
  public/images/right-arrow-pagination.png
  public/images/right-arrow.png
  public/images/share-box-active.png
  public/images/share-box.png
  public/images/share.png
  public/images/triangle-down.png
  public/images/triangle-error.png
  public/images/triangle-yellow.png
  public/images/up-active.png
  public/images/up.png
  public/images/x-mark-error.png
  public/images/x-mark-off.png
  src/app/layout.tsx
Labels: chore

#11 feat: 취약점 DB 퍼블리싱 페이지 추가
  public/images/db-bg-image-1.png
  public/images/db-bg-image-2.png
  public/images/db-bg-image-3.png
  src/app/vulnerability-db/page.tsx
  src/components/vulnerability-db/ArticleList.tsx
  src/components/vulnerability-db/ArticleListItem.tsx
  src/components/vulnerability-db/Buttons.tsx
  src/components/vulnerability-db/Chips.tsx
  src/components/vulnerability-db/LockModal.tsx
  src/components/vulnerability-db/Pagination.tsx
  src/components/vulnerability-db/RealTimeTopic.tsx
  src/components/vulnerability-db/TopThree.tsx
  src/components/vulnerability-db/TopThreeItem.tsx
  src/css/globals.css
Labels: feat

#13 feat: GNB, FOOTER 퍼블리싱 초기
  public/images/bug.svg
  public/images/sfacspace.svg
  public/next.svg
  public/vercel.svg
  src/app/layout.tsx
  src/components/common/Footer.tsx
  src/components/common/Gnb.tsx
Labels: feat

#16 fix: 취약점 DB Top 3 리스트 보여주는 방식 수정
  src/components/vulnerability-db/TopThree.tsx
  src/components/vulnerability-db/TopThreeItem.tsx
Labels: fix

#18 feat: 취약점 DB 상세 페이지 퍼블리싱
  src/app/vulnerability-db/[id]/page.tsx
  src/components/vulnerability-db/ArticleList.tsx
  src/components/vulnerability-db/ArticleListItem.tsx
  src/components/vulnerability-db/Buttons.tsx
  src/components/vulnerability-db/Chips.tsx
  src/components/vulnerability-db/LockModal.tsx
  src/components/vulnerability-db/Pagination.tsx
  src/components/vulnerability-db/RealTimeTopic.tsx
  src/components/vulnerability-db/TopThreeItem.tsx
  src/components/vulnerability-db/detail/DetailContent.tsx
  src/components/vulnerability-db/detail/SimilarCard.tsx
  src/components/vulnerability-db/detail/SimilarContent.tsx
  src/components/vulnerability-db/detail/SimilarContentList.tsx
  src/components/vulnerability-db/detail/Table.tsx
  src/components/vulnerability-db/detail/TableBodyTr.tsx
  src/components/vulnerability-db/detail/TableHead.tsx
  src/components/vulnerability-db/dummydata.ts
Labels: feat

#19 feat : 코드 검사 페이지 퍼블리싱
  src/app/ai-analyze/page.tsx
  src/app/analyze/page.tsx
  src/app/me/(analyze)/analyze/page.tsx
  src/app/me/(analyze)/data.ts
  src/app/me/(analyze)/type.ts
  src/components/analyze/AnalysisWrapper.tsx
  src/components/analyze/CodeArea.tsx
  src/components/analyze/FileList.tsx
  src/components/analyze/FileListItem.tsx
  src/components/analyze/InputChips.tsx
  src/components/analyze/ProgressBar.tsx
  src/components/analyze/ProgressList.tsx
  src/css/globals.css
Labels: feat

#23 fix: 이미지 경로 수정 및 UI 오류 수정
  src/components/vulnerability-db/ArticleListItem.tsx
  src/components/vulnerability-db/Pagination.tsx
  src/components/vulnerability-db/TopThreeItem.tsx
  src/components/vulnerability-db/detail/DetailContent.tsx
  src/components/vulnerability-db/detail/SimilarCard.tsx
  src/components/vulnerability-db/detail/TableBodyTr.tsx
  src/components/vulnerability-db/dummydata.ts
Labels: fix

#27 feat : 코드 검사 결과 페이지 퍼블리싱
  src/app/me/(analyze)/ai-analyze/page.tsx
  src/app/me/(analyze)/analyze/page.tsx
  src/app/me/(analyze)/data.ts
  src/app/me/(analyze)/type.ts
  src/components/analyze/AnalysisWrapper.tsx
  src/components/analyze/CodeArea.tsx
  src/components/analyze/FileList.tsx
  src/components/analyze/FileListItem.tsx
  src/components/analyze/FileSideBar.tsx
  src/components/analyze/Infobox.tsx
  src/components/analyze/InputChips.tsx
  src/components/analyze/ProgressBar.tsx
  src/components/analyze/ProgressList.tsx
  src/components/analyze/StateItem.tsx
  src/components/analyze/ai-analyze/FileAnalysisItem.tsx
  src/components/analyze/ai-analyze/FileAnalysisList.tsx
  src/components/analyze/ai-analyze/FileAnalysisSideBar.tsx
Labels: feat

#29 모달 컨테이너 생성
  package.json
  src/app/layout.tsx
  src/components/landing/CardArticle.tsx
  src/components/modal/ModalContainer.tsx
  src/components/modal/ModalProvider.tsx
  src/hook/useOutSideClick.ts
  src/store/modalState.tsx
Labels: feat

#30 TOP 버튼 추가
  src/app/page.tsx
  src/components/landing/TopButton.tsx
  src/components/landing/head-article/CaretDoubleDown.tsx
  src/css/swiperStyles.css
Labels: chore, feat

#33 feat: 이용약관 페이지 추가
  public/images/bg-circles.png
  src/app/doc/terms-of-service/page.tsx
Labels: feat

#36 로그인 페이지 퍼블리싱 및 문의하기 Form작업
  package.json
  public/images/bug-deco.svg
  public/images/github.svg
  public/images/up-active.svg
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/components/common/Footer.tsx
  src/components/common/Support.tsx
  src/components/common/button/CloseModalButton.tsx
  src/components/landing/CardArticle.tsx
  src/components/landing/HeadArticle.tsx
  src/components/landing/SecondArticle.tsx
  src/components/landing/ServiceArticle.tsx
  src/components/landing/ThirdArticle.tsx
  src/components/landing/card/Card.tsx
  src/components/landing/card/CardList.tsx
  src/components/landing/card/Label.tsx
  src/components/landing/head-article/CaretDoubleDown.tsx
  src/components/landing/head-article/HeadArticle.tsx
  src/components/landing/head-article/LoginButton.tsx
  src/components/landing/head-article/TopButton.tsx
  src/components/login/GithubLogin.tsx
  src/components/modal/ModalContainer.tsx
  src/components/modal/ModalProvider.tsx
  src/components/modal/SupportMessageModal.tsx
  src/store/modalState.tsx
Labels: feat

#37 fix: 취약점 DB 페이지 수정
  src/app/vulnerability-db/[id]/page.tsx
  src/app/vulnerability-db/page.tsx
  src/components/vulnerability-db/ArticleList.tsx
  src/components/vulnerability-db/ArticleListItem.tsx
  src/components/vulnerability-db/Buttons.tsx
  src/components/vulnerability-db/Chips.tsx
  src/components/vulnerability-db/LockModal.tsx
  src/components/vulnerability-db/MainContainer.tsx
  src/components/vulnerability-db/Pagination.tsx
  src/components/vulnerability-db/RealTimeTopic.tsx
  src/components/vulnerability-db/TopThree.tsx
  src/components/vulnerability-db/TopThreeItem.tsx
  src/components/vulnerability-db/detail/DetailContent.tsx
  src/components/vulnerability-db/detail/SimilarCard.tsx
  src/components/vulnerability-db/detail/SimilarContent.tsx
  src/components/vulnerability-db/detail/SimilarContentList.tsx
  src/components/vulnerability-db/detail/Table.tsx
  src/components/vulnerability-db/detail/TableBodyTr.tsx
  src/components/vulnerability-db/detail/TableHead.tsx
  src/components/vulnerability-detail/DetailContent.tsx
  src/components/vulnerability-detail/GuideText.tsx
  src/components/vulnerability-detail/SimilarCard.tsx
  src/components/vulnerability-detail/SimilarContent.tsx
  src/components/vulnerability-detail/SimilarContentList.tsx
  src/components/vulnerability-detail/Table.tsx
  src/components/vulnerability-detail/TableBodyTr.tsx
  src/components/vulnerability-detail/TableHead.tsx
  src/components/vulnerability-detail/detaildummydata.ts
Labels: fix

#38 FEAT:마이페이지 퍼블리싱
  public/images/profile.png
  src/app/me/clip/page.tsx
  src/app/me/detected/page.tsx
  src/app/me/my-profile/page.tsx
  src/app/me/page.tsx
  src/app/me/setting/page.tsx
  src/components/me/ClippingArticleItem.tsx
  src/components/me/DetectedListItem.tsx
  src/components/me/GitListItem.tsx
  src/components/me/LibrarySort.tsx
  src/components/me/ProfileInfo.tsx
  src/components/me/ProfileInfoList.tsx
  src/components/me/Sort.tsx
  src/components/me/ToggleSwitch.tsx
  tailwind.config.ts
Labels: feat

#40 github OAuth 연동, firebase 설치 및 초기세팅, 사용자 정보 fireStore 등록
  next.config.mjs
  package.json
  src/app/api/auth/[...nextauth]/route.ts
  src/auth.config.ts
  src/auth.ts
  src/components/common/Gnb.tsx
  src/components/landing/head-article/LoginButton.tsx
  src/components/login/GithubLogin.tsx
  src/firebase/firebaseClient.ts
  src/lib/.gitkeep
  src/lib/getSession.ts
  src/middleware.ts
  src/server/user.action.ts
Labels: feat

#47 fix: landing page Error
  src/app/globals.css
  src/app/layout.tsx
  src/app/login/page.tsx
  src/components/common/Footer.tsx
  src/components/common/Gnb.tsx
  src/components/landing/head-article/CaretDoubleDown.tsx
  src/components/landing/head-article/HeadArticle.tsx
  src/components/landing/head-article/TopButton.tsx
  tailwind.config.ts
Labels: chore

#49 feat 유저정보 전역상태관리
  src/app/me/my-profile/page.tsx
  src/app/me/page.tsx
  src/app/me/setting/page.tsx
  src/components/me/ProfileInfo.tsx
  src/components/me/ProfileInfoList.tsx
  src/store/useAuth.ts
Labels: feat

#51 feat: pretendard font 추가
  src/app/layout.tsx
  src/fonts/PretendardVariable.woff2
  tailwind.config.ts
Labels: chore, feat
