Repository FlawDetector-team-yes/FlawDetector-team-yes, pull requests merged in 2024-09, with the labels that each got.

#63 Feature/analyze
  package.json
  src/app/me/(analyze)/data.ts
  src/app/me/repos/[id]/[inspection]/page.tsx
  src/app/me/repos/[id]/page.tsx
  src/app/me/repos/type.ts
  src/components/analyze/AnalysisWrapper.tsx
  src/components/analyze/CodeArea.tsx
  src/components/analyze/CodeViewer.tsx
  src/components/analyze/FileList.tsx
  src/components/analyze/FileListItem.tsx
  src/components/analyze/ai-analyze/FileAnalysisList.tsx
  src/components/analyze/ai-analyze/FileAnalysisSideBar.tsx
  src/components/analyze/analyze-modal/ModalFileListItem.tsx
  src/store/useFilesStore.tsx
  src/store/useSelectedFilesStore.tsx
Labels: feat

#65 feat: 검사하기 모달 llm api 및 worker 연결, 모달 진행도 표시, UI 수정
  public/images/bug-white.svg
  public/images/circle-x-mark.png
  src/app/api/analyze/llm/route.ts
  src/app/layout.tsx
  src/components/analyze/AnalysisWrapper.tsx
  src/components/analyze/CodeViewer.tsx
  src/components/analyze/OpenModalBtn.tsx
  src/components/analyze/analyze-modal/AnalysisModal.tsx
  src/components/analyze/analyze-modal/ModalFileListItem.tsx
  src/store/useAnalyzeStore.tsx
  src/worker/analyzeWorker.ts
Labels: feat, fix

#74 feat: 데이터 크롤링 및 db저장
  package.json
  src/scripts/addDataToFirebase.js
  src/scripts/crawling.js
  src/scripts/fetch-token.js
  src/scripts/parseTextToArray.ts
  src/scripts/trans.js
  tsconfig.json
Labels: feat

#81 feat : 마이페이지 사용자 Github 정보 연결 및 디자인 변경
  public/images/right-arrow-white.svg
  public/images/star-purple.svg
  public/images/star-white.svg
  src/app/api/github/repos/[owner]/route.ts
  src/app/api/github/user/[userNumber]/route.ts
  src/app/me/detected/page.tsx
  src/app/me/page.tsx
  src/components/analyze/AnalysisWrapper.tsx
  src/components/analyze/CodeViewer.tsx
  src/components/analyze/FileList.tsx
  src/components/analyze/FileListItem.tsx
  src/components/me/ClippingArticleItem.tsx
  src/components/me/DetectedListItem.tsx
  src/components/me/GitListItem.tsx
  src/components/me/GitRepoList.tsx
  src/components/me/GitRepoListItem.tsx
  src/components/me/GitRepoListLoading.tsx
  src/components/me/LibrarySort.tsx
  src/components/me/ProfileInfo.tsx
  src/components/me/ProfileInfoList.tsx
  src/components/me/RepoSortDropdown.tsx
  src/components/me/Sort.tsx
  src/store/useAuth.ts
  src/store/useSelectedFilesStore.tsx
  src/store/useUserStore.ts
Labels: feat

#72 feat: 코드 검사 진행 상태 표시 추가, toast 추가, 검사 중지 오류 수정
  package.json
  public/images/hourglass.png
  public/images/loading-arrow.png
  src/components/analyze/AnalysisWrapper.tsx
  src/components/analyze/FileListItem.tsx
  src/components/analyze/FileSideBar.tsx
  src/components/analyze/OpenModalBtn.tsx
  src/components/analyze/StateItem.tsx
  src/components/analyze/ToastBox.tsx
  src/components/analyze/analyze-modal/AnalysisModal.tsx
  src/components/modal/ModalContainer.tsx
  src/store/useAnalyzeStore.tsx
  src/worker/analyzeWorker.ts
Labels: feat, fix

#83 feat: 사용자 탈퇴 로직 추가, 로그아웃 버튼 디자인 수정, image src 오류 수정
  public/images/basic-user.png
  src/components/common/Gnb.tsx
  src/components/me/ProfileInfo.tsx
  src/components/me/UserProfile.tsx
  src/components/me/UserProfileBtn.tsx
  src/middleware.ts
Labels: feat, fix

#87 검사 페이지 폴더 이동 및 데이터 로드 오류 수정, Github api 함수 리팩토링
  src/components/analyze/FileList.tsx
  src/components/analyze/FileListItem.tsx
  src/components/login/GithubLogin.tsx
  src/components/me/GitRepoList.tsx
  src/components/me/GitRepoListItem.tsx
  src/components/me/GitRepoListLoading.tsx
  src/components/me/RepoSortDropdown.tsx
  src/lib/api/github/fetchRepoContents.ts
  src/lib/api/github/fetchUserInfo.ts
  src/lib/api/github/fetchUserRepos.ts
  src/store/useFilesStore.tsx
  src/store/useUserStore.ts
Labels: bug, fix

#91 feat: 사용자 별 검사 결과 fireStore 저장, reposState 추가
  public/images/download.png
  src/app/layout.tsx
  src/auth.config.ts
  src/components/analyze/AnalysisWrapper.tsx
  src/components/analyze/FileListItem.tsx
  src/components/analyze/analyze-modal/AnalysisModal.tsx
  src/components/modal/ModalContainer.tsx
  src/components/modal/ModalProvider.tsx
  src/store/useAnalyzeStore.tsx
Labels: feat

#89 fix: 크롤링 페이지네이션 오류 해결
  src/scripts/crawling.mjs
Labels: bug, fix

#99 fix : 마이페이지, 코드 검사 페이지 다중 레포지토리 동시 검사 중 발생하는 버그 수정 및 로직 개선
  src/app/me/repos/type.ts
  src/components/analyze/AnalysisWrapper.tsx
  src/components/analyze/FileListItem.tsx
  src/components/analyze/FileSideBar.tsx
  src/components/analyze/OpenModalBtn.tsx
  src/components/analyze/analyze-modal/AnalysisModal.tsx
  src/components/analyze/analyze-modal/ModalFileList.tsx
  src/components/common/Support.tsx
  src/components/common/button/CloseModalButton.tsx
  src/components/me/GitRepoList.tsx
  src/components/me/GitRepoListItem.tsx
  src/components/me/UserProfile.tsx
  src/components/modal/ModalContainer.tsx
  src/components/modal/ModalProvider.tsx
  src/hook/useOutSideClick.ts
  src/store/useAnalyzeStore.tsx
  src/store/useModalStore.tsx
  src/store/useSelectedFilesStore.tsx
Labels: bug, fix

#102 Feature/vulnerability db
  src/app/api/vulnerabilities/route.ts
  src/app/vulnerability-db/[id]/loading.tsx
  src/app/vulnerability-db/loading.tsx
  src/app/vulnerability-db/page.tsx
  src/components/vulnerability-db/ArticleList.tsx
  src/components/vulnerability-db/ArticleListItem.tsx
  src/components/vulnerability-db/Buttons.tsx
  src/components/vulnerability-db/Chips.tsx
  src/components/vulnerability-db/MainContainer.tsx
  src/components/vulnerability-db/TopThree.tsx
  src/components/vulnerability-db/TopThreeAndSetData.tsx
  src/components/vulnerability-db/TopThreeItem.tsx
  src/components/vulnerability-db/TopThreeLoading.tsx
  src/components/vulnerability-detail/DetailContent.tsx
  src/components/vulnerability-detail/SimilarCard.tsx
  src/components/vulnerability-detail/Table.tsx
  src/components/vulnerability-detail/TableBodyTr.tsx
  src/components/vulnerability-detail/getDetailData.ts
  src/scripts/addDataToFirebase.js
  src/store/useHotNewState.tsx
  src/store/useVulnerabilityStore.ts
Labels: feat

#104 FEAT: 챗봇 생성 및 기능 구현
  public/images/bg-bug-icon.svg
  public/images/chatBot-submit.svg
  src/app/api/chatBot/route.ts
  src/components/chatBot/AiResponse.tsx
  src/components/chatBot/ChatBot.tsx
  src/components/chatBot/TextInput.tsx
  src/components/chatBot/UserRequest.tsx
  src/store/chatBotStore.tsx
Labels: feat

#108 fix: 배포 이미지 경로 수정
  src/components/me/GitRepoList.tsx
  src/components/me/RepoSortDropdown.tsx
Labels: fix

#109 fix: #107 배포 이미지 경로 다시 수정
  src/components/me/RepoSortDropdown.tsx
Labels: fix

#112 fix: 개인정보처리방침, 서비스이용약관 ul 태그 div 태그로 수정, li 태그 pre 태그로 수정
  src/app/doc/privacy-policy/page.tsx
  src/app/doc/terms-of-service/page.tsx
Labels: fix

#113 fix: 개인정보처리방침, 서비스이용약관 따옴표 quot 수정
  src/app/doc/privacy-policy/page.tsx
  src/app/doc/terms-of-service/page.tsx
Labels: fix

#115 fix: #107 배포 오류 수정(route handler 오류)
  src/app/api/analyze/repository/route.ts
  src/lib/sortDirOverFiles.ts
Labels: fix

#116 fix : #107 정적 -> 동적 서버 렌더링 문제 해결
  src/app/api/analyze/repository/route.ts
Labels: bug

#117 feat, refactor: 취약점 DB페이지 및 상세페이지 리팩토링 및 기능추가
  package.json
  public/images/magnifying-glass.svg
  src/app/layout.tsx
  src/app/vulnerability-db/[id]/loading.tsx
  src/app/vulnerability-db/[id]/page.tsx
  src/app/vulnerability-db/loading.tsx
  src/app/vulnerability-db/page.tsx
  src/components/common/Gnb.tsx
  src/components/vulnerability-db/ArticleList.tsx
  src/components/vulnerability-db/Chips.tsx
  src/components/vulnerability-db/LockModal.tsx
  src/components/vulnerability-db/MainContainer.tsx
  src/components/vulnerability-db/Pagination.tsx
  src/components/vulnerability-db/RealTimeTopic.tsx
  src/components/vulnerability-db/SearchBar.tsx
  src/components/vulnerability-detail/DetailContent.tsx
  src/components/vulnerability-detail/PinButton.tsx
  src/components/vulnerability-detail/ShareButton.tsx
  src/components/vulnerability-detail/Table.tsx
  src/components/vulnerability-detail/TableBodyTr.tsx
  src/components/vulnerability-detail/useDetailData.ts
  src/firebase/addOrUpdateRealTimeTopic.ts
  src/firebase/fetchDetailVulnerability.ts
  src/firebase/fetchRealTimeTopics.ts
  src/types/.gitkeep
  src/types/common.ts
  src/types/vulnerability.ts
Labels: feat

#128 Feature/analyze
  src/app/me/clip/page.tsx
  src/app/vulnerability-db/[id]/page.tsx
  src/components/landing/ThirdArticle.tsx
Labels: fix

#129 fix: 배포 오류 수정(이미지, 컴포넌트명 수정)
  src/app/vulnerability-db/[id]/page.tsx
  src/components/landing/ThirdArticle.tsx
Labels: bug

#123 fix: 검사 결과 페이지 에러 핸들링 코드 수정 및 페이지 규격 수정
  src/app/api/analyze/llm/route.ts
  src/app/me/repos/[id]/[inspection]/page.tsx
  src/app/me/repos/[id]/page.tsx
  src/components/analyze/AnalysisWrapper.tsx
  src/components/analyze/FileListItem.tsx
  src/components/analyze/StateItem.tsx
  src/components/analyze/ai-analyze/FileAnalysisList.tsx
  src/components/analyze/ai-analyze/FileAnalysisListContainer.tsx
  src/components/analyze/ai-analyze/FileAnalysisSideBar.tsx
  src/components/analyze/ai-analyze/Infobox.tsx
  src/components/analyze/ai-analyze/ModifiedCode.tsx
  src/components/analyze/ai-analyze/ResCodeViewer.tsx
  src/components/analyze/ai-analyze/anlaysisResultMsg.ts
  src/components/analyze/ai-analyze/dummydata.ts
  src/components/analyze/analyze-modal/AnalysisModal.tsx
  src/components/common/Footer.tsx
  src/components/me/GitRepoList.tsx
  src/lib/getFileLanguage.ts
  src/store/useAnalyzeStore.tsx
Labels: bug, fix

#130 클립 페이지 생성
  package.json
  public/images/triangle-up.svg
  src/app/layout.tsx
  src/app/me/clip/page.tsx
  src/app/vulnerability-db/[id]/page.tsx
  src/app/vulnerability-db/page.tsx
  src/components/common/Clip.tsx
  src/components/common/Footer.tsx
  src/components/me/ClippingArticleItem.tsx
  src/components/me/SortDropdown.tsx
  src/components/vulnerability-db/ArticleList.tsx
  src/components/vulnerability-db/ArticleListItem.tsx
  src/components/vulnerability-db/Buttons.tsx
  src/components/vulnerability-db/Chips.tsx
  src/components/vulnerability-db/ClipPagination.tsx
  src/components/vulnerability-db/LockModal.tsx
  src/components/vulnerability-db/MainContainer.tsx
  src/components/vulnerability-db/RealTimeTopic.tsx
  src/components/vulnerability-db/TopThreeAndSetData.tsx
  src/components/vulnerability-detail/DetailContent.tsx
  src/components/vulnerability-detail/Table.tsx
  src/firebase/fetchPinnedId.ts
  src/firebase/fetchTenthHotData.ts
  src/firebase/useFetchPin.ts
  src/store/usePinnedStore.ts
Labels: feat

#131 fix : 코드 검사 페이지에서 파일명이 길 경우 UI 박스를 벗어나는 문제 해결
  src/app/layout.tsx
  src/app/robots.ts
  src/app/sitemap.ts
  src/components/analyze/FileList.tsx
  src/components/analyze/FileListItem.tsx
Labels: bug

#132 fix : #107 배포 오류 수정(metadata 중복 삭제)
  src/app/vulnerability-db/[id]/page.tsx
Labels: bug

#134 feat : 마이페이지 레포지토리 검사 상태 정렬 기능 추가
  src/app/api/analyze/llm/route.ts
  src/app/me/repos/[id]/page.tsx
  src/components/analyze/AnalysisWrapper.tsx
  src/components/analyze/AnalyzeHeader.tsx
  src/components/analyze/CodeViewer.tsx
  src/components/analyze/FileListItem.tsx
  src/components/analyze/ai-analyze/FileAnalysisSideBar.tsx
  src/components/analyze/ai-analyze/Infobox.tsx
  src/components/analyze/ai-analyze/ResCodeViewer.tsx
  src/components/analyze/analyze-modal/AnalysisModal.tsx
  src/components/analyze/analyze-modal/ModalFileList.tsx
  src/components/analyze/analyze-modal/ModalFileListItem.tsx
  src/components/chatBot/TextInput.tsx
  src/components/common/Support.tsx
  src/components/me/GitRepoList.tsx
  src/components/me/RepoSortDropdown.tsx
  src/components/me/ToggleSwitch.tsx
  src/components/modal/SupportMessageModal.tsx
  src/components/vulnerability-detail/Table.tsx
  src/firebase/fetchPin.ts
Labels: feat

#135 스크랩(핀 된 게시물) 페이지 읽기 요청 최소화
  src/components/me/ClippingArticleItem.tsx
  src/components/vulnerability-db/ClipPagination.tsx
Labels: fix

#137 style: 검사 페이지 검출 총계 UI 수정, 검사 페이지 검사 UI header 수정
  src/app/me/repos/[id]/page.tsx
  src/components/analyze/AnalyzeHeader.tsx
  src/components/analyze/FileSideBar.tsx
Labels: style

#138 fix: pretendard 폰트 적용
  src/app/api/analyze/llm/route.ts
  src/app/api/chatBot/route.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/me/my-profile/page.tsx
  src/app/me/page.tsx
  src/app/me/setting/page.tsx
  src/components/common/Footer.tsx
  src/components/common/Support.tsx
  src/components/landing/ThirdArticle.tsx
  src/components/landing/card/Card.tsx
  src/components/login/GithubLogin.tsx
  src/components/modal/SupportMessageModal.tsx
  src/components/vulnerability-db/ArticleListItem.tsx
  src/scripts/crawling.mjs
  src/scripts/fetch-token.js
  src/scripts/trans.js
Labels: chore

#139 fix: 취약점DB 검색어 처리
  src/components/vulnerability-db/MainContainer.tsx
Labels: fix

#140 refactor : 파비콘 구글 검색에 노출될 수 있게 변경
  src/app/layout.tsx
Labels: fix

#141 refactor : 오픈그래프 타이틀 수정
  src/app/layout.tsx
Labels: fix

#142 Update README.md
  README.md
Labels: feat

#149 Update README.md 초안
  README.md
Labels: chore

#150 style: 디자인 이슈 수정
  src/components/me/ClippingArticleItem.tsx
Labels: style

#152 챗봇 오류해결
  package.json
  src/app/api/chatBot/route.ts
  src/app/api/email/route.ts
  src/app/vulnerability-db/[id]/page.tsx
  src/app/vulnerability-db/page.tsx
  src/components/chatBot/AiResponse.tsx
  src/components/chatBot/ChatBot.tsx
  src/components/chatBot/FolderResult.tsx
  src/components/chatBot/Loading.tsx
  src/components/chatBot/TextInput.tsx
  src/components/common/Support.tsx
  src/hook/emailer.ts
  src/store/chatBotStore.tsx
Labels: bug, fix
